giphy:
    apikey: your-api-key
    url: https://api.giphy.com/v1/gifs
micronaut:
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:static"
